import Head from 'next/head'
import Faculty from '../../components/Faculty2.0/faculty';
import Layout from '../../components/Faculty2.0/Layout';
import styles from '../../styles/Home.module.css';

export default function Home() {
  return (
    <Layout>
    <div>
      <Head>
        <title>Faculty Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/static2.0/KRMU_LOGO.png" />
      </Head>
      <main className={styles.description}>
        <h1 class="text-2xl lg:text-5xl lg:mt-12 lg:mb-5 italic text-blue-600">
          Faculty
        </h1>
        <p class="my-2 text-md text-left lg:text-2xl lg:my-3">
          Well-experienced and distinguished faculty that works diligently to
          transform students into the most desirable personalities every
          industry demands. These through leaders connect with the students to
          identify their career interests and offer them personalized
          mentorship, enabling them to shine in their respective professions.
        </p>
        <div class="mt-8 flex flex-wrap items-center justify-center text-white gap-y-20 gap-x-20">
        <Faculty/>
        <Faculty/>
        <Faculty/>
        <Faculty/>
        <Faculty/>
        <Faculty/>
        <Faculty/>
        </div>
      </main>
    </div>
    </Layout>
  )
}
